### ISSUE TITLE
Variable block times

### ISSUE THREAD

**Issue by Reecepbcups** [eve-network/eve#7]
3 min block heartbeat

Sei Network config root.go commit timeout
& emoney for pulse

**Comment by faddat** [comment]
allllllmost done. 

Yeah I do think that basically we will want to have -- not Sei's commit timeout, because it is too fast.  1 second is OK though, I've tested that with osmosis and evmos.  

evmos validators only really miss so many blocks because they have widespread trouble connecting to each other, I think.
